### ISSUE TITLE
Snap package doesn't start

### ISSUE THREAD

**Issue by NatoBoram** [Siderus/Orion#203]
**Describe the bug**

The application doesn't open, instead crashes with the following error message : 

```log
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Failed to generate minidump.Segmentation fault (core dumped)
```

**To Reproduce**
1. `sudo snap install orion`
2. `orion`

**Expected behavior**

The application should start

**Screenshots**

![image](https://user-images.githubusercontent.com/10495562/46318874-fa097680-c5a5-11e8-9df1-d4719fb15964.png)

**Desktop (please complete the following information):**

OS

```yaml
OS: Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.15.0-34-generic 
Uptime: 18 hours, 55 mins 
Packages: 1785 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: Budgie 
WM: Mutter(Budgie) 
Theme: Pocillo-dark [GTK2/3] 
Icons: Pocillo [GTK2/3] 
Terminal: tilix 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 2930MiB / 7922MiB 
```

Browser

```yaml
Package: firefox
Version: 62.0+build2-0ubuntu0.18.04.5
Priority: optional
Section: web
Origin: Ubuntu
Maintainer: Ubuntu Mozilla Team <ubuntu-mozillateam@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 173 MB
Provides: gnome-www-browser, iceweasel, www-browser
```

Orion

```yaml
name:      orion
summary:   Orion
publisher: Lorenzo Setale (koalalorenzo)
license:   unset
description: |
  Siderus Orion is an easy-to-use IPFS desktop client
commands:
  - orion
snap-id:      nugqnJRp7c03UjdoQxsp9xwWF1swIIEI
tracking:     stable
refresh-date: today at 18:13 EDT
```

**Additional context**

Fresh Ubuntu Budgie 18.04 install, with IPFS installed and running.
